language: csharp

mono: 5.12.0

dotnet: 3.1.101

install:

  # workaround for missing .net 4.5 

  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  
before_install:
  - chmod +x fake.sh
 
matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet : 3.1.101
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dotnet : 3.1.101
      dist: trusty
      sudo: required

script: 
  - ./fake.sh build target all

branches:
  except:
    - gh-pages